### ISSUE TITLE
Specific Master Account reference not working

### ISSUE THREAD

**Issue by tstroband** [OlafConijn/AwsOrganizationFormation#14]
It seems that a reference to the master account is not working properly.
Consider the following fragment:
```
  RootHostedZone:
    Type: AWS::Route53::HostedZone
    OrganizationBindings:
      Regions: eu-west-1
      Accounts: !Ref MasterAccount
    Properties:
      ...
```

Here the reference to the master account yields the following error message:
```
ERROR: unable to load file somefile.yml, reason: unable to find resource named MasterAccount
```

A workaround is not specifying any account but to use the include-master property:
```
  RootHostedZone:
    Type: AWS::Route53::HostedZone
    OrganizationBindings:
      Regions: eu-west-1
      IncludeMasterAccount: true
    Properties:
      ...
```
