### ISSUE TITLE
Support for serverless framework tasks

### ISSUE THREAD

**Issue by eduardomourar** [OlafConijn/AwsOrganizationFormation#39]
We need to be able to use the OrgFormation tasks to deploy a serverless framework workload to one or more AWS accounts.

**Comment by OlafConijn** [comment]
yes, sounds great. something like:
```
ServerlessWorkload:
  Type: update-serverless.org              # type
  Config: ./workload/serverless.yml.       # serverless file, optional
  Path: ./workload/                        # used to package / calculate hash
  OrganizationBinding:
    AccountsWithTag: selective-few
  MaxConcurrentStacks: 10
  FailedStackTolerance: 10
```
