### ISSUE TITLE
[Question] Add users to account

### ISSUE THREAD

**Issue by hffmnn** [OlafConijn/AwsOrganizationFormation#58]
I'd like to add new users to the newly created account in an OU. Is there an example on how to do that? Or is this tool not meant to do that?

**Comment by OlafConijn** [comment]
hi,

Yes, you would be able to do that. The tools can be used to create accounts, ou's and resources within these accounts using code. 

Resources can be created in cloudformation (with some annotations)

mytemplate.yml
``` yaml
AWSTemplateFormatVersion: '2010-09-09-OC'

# Include file used to manage the Organization (accounts, ou's, etc).
# accounts in this file can be used to deploy resources to
Organization: !Include ../organization.yml

Resources:
  OriginBucket:
    Type: AWS::IAM::User
    OrganizationBinding: 
      Accounts:
      - !Ref MyAccount1
      - !Ref MyAccount2
    Properties:
      UserName: abcdef
```

This template can be used to create a used called abcdef in accounts MyAccount1 and MyAccount2 (which are expected to be found in the file that is used to manage the organization resources).

you can update the users in both accounts using:
```
\> org-formation update-stacks mytemplate.yml --stack-name my-stack
```

documentation on users created by cloudformation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html#cfn-iam-user-username
