### ISSUE TITLE
[CDK task] parameter support (-c)

### ISSUE THREAD

**Issue by OlafConijn** [OlafConijn/AwsOrganizationFormation#61]
it would be nice to support passing parameters to the CDK workload from within tasks. These parameters should be translated to -c arguments on the `deploy` and `remove` command (e.g. `-c param=val -c param2=val`).

for the CustomDeployCommand and CustomRemoveCommand we could introduce a variable that gets substituted with the parameter string. e.g. `!Sub npm ci && npm run build && npx cdk deploy ${Task::Parameters} --requireApproval `

```
MyCdkSomething:
  Type: update-cdk
  Path: ./cdk/
  Parameters:
    orgPrefix: myorg
    multiAZ: false
    instanceType: db.t3.medium
    allocatedStorage: 20
```
