### ISSUE TITLE
Environment Variables on SLS and CDK Invocations

### ISSUE THREAD

**Issue by OlafConijn** [OlafConijn/AwsOrganizationFormation#64]
Would be nice to pass environment variables to tools that are executed on the commandline.
Implementation would be on CustomDeployCommand/CustomRemoveCommand and could be backwards compatible with the current commands.

env variables would be able to overwrite everything, except for the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` passed as environment variables by org-formation.

``` yaml
  CustomDeployCommand:
    cmd: npm ci && npm run build && npx cdk deploy
    env: 
      SOME_VAR: some-value 
      ANOTHER_SOME_VAR: another-value 
```
or
``` yaml
  CustomDeployCommand:
    cmd: npm ci && npm run build && npx cdk deploy
    env: { SOME_VAR: some-value, ANOTHER_SOME_VAR: another-value} 
```
