### ISSUE TITLE
[Question] Reference AccountId in Taskfile

### ISSUE THREAD

**Issue by hffmnn** [OlafConijn/AwsOrganizationFormation#66]
Given I have generated an `AWS::IAM::ManagedPolicy` in one specific account, I'd like to set the arn of this policy on a role via a Task file, basically the same use case as the [cross account role](https://github.com/OlafConijn/AwsOrganizationFormation/tree/master/examples#cross-account-role).

Now the arn looks something like this: `arn:aws:iam::<accountID>:policy/my-special-policy`. The question: how to get the accountId dynamically in the Taskfile as I don't want to hardcode that?

**Comment by OlafConijn** [comment]
hi!

In the current version (0.9.4 latest) you are indeed not able to do this. 
In 0.9.5-beta.5 however....... you can do any of the following in the tasks file:

``` yaml
MyTask:
  Type: update-stacks
  Template: ./template.yml
  StackName: example
  DefaultOrganizationBindingRegion: eu-west-1
  DefaultOrganizationBinding:
    IncludeMasterAccount: true
  Parameters:
    tagVal: !GetAtt MasterAccount.Tags.Tag
    masterAccountId: !Ref MasterAccount  # any logical account id from the organization file 
    masterAccountId2: !GetAtt MasterAccount.AccountId # GetAtt to get AccountId or other attributes
    awsAccountId: !Ref AWS::AccountId.  # resolves to the target account
    someSubExpression: !Sub
    - '${example1}--${example2}'
    - {example1: !GetAtt MasterAccount.AccountId, example2: !Ref AWS::AccountId}
    currentAccount: !Ref CurrentAccount   # resolves to the target account
```

**Comment by hffmnn** [comment]
Nice! Thanks a lot for that.

With export you mean a typical export via a CloudFormation `Outputs`?

**Comment by OlafConijn** [comment]
yes. output or export (i am always confused with the terminology here :)).

It is a bit like `!ImportValue` except for it doesn't create a reference that would prevent you from deleting the stack that has the Output. Hence `!CopyValue`.

3 ways to use this function:
``` yaml
    param: !CopyValue Export
    param: !CopyValue [Export, 1231231231231]
    param: !CopyValue [Export, 1231231231231, 'eu-west-1']
```

if `accountId` or `region` are omitted it will use the target account. If you have a binding to multiple accounts the target account will obviously be different for the different targets.

This is also not available in `0.9.4` (but in `0.9.5-beta.5`).
