### ISSUE TITLE
aws cdk

### ISSUE THREAD

**Issue by lielran** [OlafConijn/AwsOrganizationFormation#77]
I see that you are using part of aws-cdk but only for test purposes. 
what do you think of using cdk instead of cloudformation ymls?

**Comment by lielran** [comment]
Thanks @OlafConijn. I'll give it a try

**Comment by lielran** [comment]
@OlafConijn - quick question about `update-cdk`. is it possible to reference AccountId? so cdk could create CFN stack for each account in OU? 

can you share an example with cdk?

**Comment by OlafConijn** [comment]
hi, if you change the binding to `OrganizationalUnit: !Ref MyOU` the cdk project will be deployed to every account in the OU.
you can pass the accountId as a parameter using `param1: !Sub 'sub expression ${AWS::AccountId}'`

```
OrganizationUpdate:
  Type: update-organization
  Template: ./organization.yml

CdkWorkload:
  Type: update-cdk
  Path: ./workload/
  RunNpmInstall: true
  OrganizationBinding:
    OrganizationalUnit: !Ref MyOU
  Parameters:
    param1: !Sub 'sub expression ${AWS::AccountId}'
    param2: !GetAtt AccountA.AccountName
  MaxConcurrentTasks: 1
  FailedTaskTolerance: 0
```
