### ISSUE TITLE
feature request: enable EBS default encryption at the account > region level

### ISSUE THREAD

**Issue by craighurley** [OlafConijn/AwsOrganizationFormation#84]
Hello,

It would be nice to have a feature in org-formation that enabled default EBS encryption.  Default encryption is enabled/disabled per region in a given account.

![Screen Shot 2020-08-13 at 16 44 40](https://user-images.githubusercontent.com/3684519/90095787-c98be980-dd85-11ea-9716-224bda3e2099.png)

- https://aws.amazon.com/blogs/aws/new-opt-in-to-default-encryption-for-new-ebs-volumes/
- https://docs.aws.amazon.com/cli/latest/reference/ec2/enable-ebs-encryption-by-default.html

**Comment by OlafConijn** [comment]
see: https://github.com/OlafConijn/AwsOrganizationFormation/issues/83

there might be a bunch of other account/org/region level settings come to might. will definately put this one top of the list too. :)

**Comment by OlafConijn** [comment]
hi, we are implementing a library of resource providers and this will be one.
A resource provider can be deployed to your AWS account/region and allows you to extend the CloudFormation types.

This will look like:
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  EbsEncryptionDefaults:
    Type: 'Community::Organizations::EbsEncryptionDefaults'
    Properties:
      EnableEbsEncryptionByDefault: true
```

Using org-formation you can apply these resources to multiple accounts/regions using an organization binding.
The resource providers still need some polishing and a method to easily deploy these types.

The repository can be found at: https://github.com/org-formation/aws-resource-providers.
