### ISSUE TITLE
S3 Bucket creation for CloudTrail failed

### ISSUE THREAD

**Issue by tstroband** [OlafConijn/AwsOrganizationFormation#9]
Creating a stack with the following command failed:

Command:
```org-formation update-accounts 01-cloudtrail.yml --stack-name cso-cloudtrail --profile my-profile```

Error:
```
ERROR: error updating cloudformation stack cso-cloudtrail in account 74750******* (eu-west-1). 
Resource is not in the state stackCreateComplete
ERROR: Resource CloudTrailLogGroupRole failed because Resource creation cancelled.
ERROR: Resource CloudTrailBucket failed because The XML you provided was not well-formed or did not validate against our published schema (Service: Amazon S3; Status Code: 400; Error Code: MalformedXML; Request ID: 4CD90BFE570924E8; S3 Extended Request ID: Z3ARrstSaVFaVlNV3IcUnrA/2ikpgIW7MxkXI+WGuu/XCvnEniKDTBXksrCXQNttTY+qacLhf4o=).
failed executing task: ResourceNotReady: Resource is not in the state stackCreateComplete
ERROR: unexpected error occurred...
{ ResourceNotReady: Resource is not in the state stackCreateComplete
    at constructor.setError (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
    at Request.CHECK_ACCEPTORS (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-organization-formation/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'Resource is not in the state stackCreateComplete',
  code: 'ResourceNotReady',
  retryable: false,
  time: 2019-09-28T16:49:46.349Z,
  statusCode: 200,
  retryDelay: 1000 }
```

Fragment:
```
  CloudTrailBucket:
    OrganizationBindings:
      Regions: eu-west-1
      Accounts: !Ref AuditAccount
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'cso-cloudtrail-${AWS::AccountId}'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES-256
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 365
      VersioningConfiguration:
        Status: Enabled
```
